# Change these first
owner: bitjbullock # Your GitHub organization or username, where this repository lives
repo: Uptime2 # The name of this repository

sites:
  - name: Google
    url: https://www.google.com
  - name: PointClickCare
    url: https://www60.pointclickcare.com
  - name: MediSystem
    url: https://clientcare.medisystem.ca/
  - name: Surge Learning
    url: https://www1.surgelearning.ca/
  - name: Dayforce
    url: https://www.dayforcehcm.com/mydayforce/login.aspx
  - name: Relias
    url: https://login.relias.ca/
  - name: Cihi
    url: https://secure.cihi.ca/
  - name: LTC Homes
    url: https://ltchomes.net/LTCHPortal/Login.aspx

   
    
   

status-website: 
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /Uptime2
  logoUrl: 
  name: Upptime
  introTitle: "Uptime monitor for common websites"
  introMessage: 
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
